"""first draft

Revision ID: e0e2365d5f11
Revises: 
Create Date: 2022-06-12 09:49:17.038081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e2365d5f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shoetype', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('condition', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'condition')
    op.drop_column('products', 'shoetype')
    # ### end Alembic commands ###
